[window]
decorations_theme_variant = "Dark"
dynamic_title = true
level = "AlwaysOnTop"

[window.dimensions]
columns = 80
lines = 24

[font]
size = 14

[font.normal]
family = "Source Code Pro"

[scrolling]
history = 100000

[colors.primary]
background = "0x0d1117"
foreground = "0xc9d1d9"

[colors.cursor]
cursor = "0xc9d1d9"
text = "0x0d1117"

[colors.normal]
black = "0x0d1117"
blue = "0x58a6ff"
cyan = "0x39c5cf"
green = "0x3fb950"
magenta = "0xbc8cff"
red = "0xff7b72"
white = "0xc9d1d9"
yellow = "0xffc300"

[colors.bright]
black = "0x484f58"
blue = "0x58a6ff"
cyan = "0x39c5cf"
green = "0x3fb950"
magenta = "0xbc8cff"
red = "0xff7b72"
white = "0xffffff"
yellow = "0xffc300"

[cursor]
blink_interval = 550

[cursor.style]
shape = "Beam"
blinking = "Always"
